<ul class="custom-tree">
  <li>
    Plant-based
    <ul>
      <li>
        Fruits
        <ul>
          <li>Salak</li>
          <li>Mangosteen</li>
        </ul>
      </li>
      <li>
        Veggies
        <ul>
          <li>Salsify</li>
          <li>Kohlrabi</li>
        </ul>
      </li>
    </ul>
  </li>
  <li>
    Animal-based
    <ul>
      <li>Beef</li>
      <li>Jellyfish</li>
    </ul>
  </li>
</ul>
