<ul class="custom-tree">
  <li>
    <h2>Plant-based</h2>
    <ul>
      <li>
        <h3>Fruits</h3>
        <ul>
          <li>Salak</li>
          <li>Mangosteen</li>
        </ul>
      </li>
      <li>
        <h3>Veggies</h3>
        <ul>
          <li>Salsify</li>
          <li>Kohlrabi</li>
        </ul>
      </li>
    </ul>
  </li>
  <li>
    <h2>Animal-based</h2>
    <ul>
      <li>Beef</li>
      <li>Jellyfish</li>
    </ul>
  </li>
</ul>
