name: Setup butler
description: Set up and auth/login to butler CLI

inputs:
  BUTLER_API_KEY:
    description: https://itch.io/user/settings/api-keys
    required: true

runs:
  using: composite
  steps:
    - uses: actions/cache@v5
      id: butler-cache
      with:
        path: ./butler
        key: linux-amd64-butler-${{ env.BUTLER_VER }}

    - name: Download & install butler
      if: steps.butler-cache.outputs.cache-hit != 'true'
      run: |
        curl -L -o ./butler.zip "https://broth.itch.zone/butler/linux-amd64/$BUTLER_VER/archive/default"
        unzip -o ./butler.zip
        ./butler --version
      shell: bash

    - name: Log in to butler
      run: |
        ./butler login
      shell: bash
      env:
        BUTLER_API_KEY: ${{ inputs.BUTLER_API_KEY }}
