name: Deploy app

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/deploy.yml'
      - 'package.json'
      - 'bun.lock'
      - '**/*.svelte'
      - '**/*.scss'
      - '**/*.json'
      - '**/*.js'
      - '**/*.ts'
      - 'src/'
  workflow_dispatch:

env:
  BUTLER_VER: 15.27.0

jobs:
  deploy-gh-pages: # ----------------------------------------------------------
    name: Deploy to GitHub Pages

    permissions:
      contents: read
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest

    steps:
      # TODO: make these DRY
      # Setup
      - uses: actions/checkout@v6.0.2
      - uses: oven-sh/setup-bun@v2
      - uses: actions/cache@v5
        with:
          path: ~/.bun/install/cache
          key: ${{ runner.os }}-bun-${{ hashFiles('bun.lock') }}
          restore-keys: |
            ${{ runner.os }}-bun-
      - run: bun ci

      - name: Build app
        run: |
          bun run build --base=/Pitch/

      - name: Upload GitHub Pages artifact
        uses: actions/upload-pages-artifact@v5
        with:
          path: dist/

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5
        with:
          artifact_name: github-pages

  deploy-itch: # ---------------------------------------------------------
    name: Deploy to itch.io

    runs-on: ubuntu-latest

    steps:
      # Setup
      - uses: actions/checkout@v6.0.2
      - uses: oven-sh/setup-bun@v2
      - uses: actions/cache@v5
        with:
          path: ~/.bun/install/cache
          key: ${{ runner.os }}-bun-${{ hashFiles('bun.lock') }}
          restore-keys: |
            ${{ runner.os }}-bun-
      - run: bun ci

      - name: Build app
        run: |
          bunx vite build --base="./" -- --nightly

      - uses: actions/cache@v5
        with:
          id: butler-cache
          path: ./butler
          key: linux-amd64-butler-${{ env.BUTLER_VER }}
      - name: Download & install butler
        if: steps.butler-cache.outputs.cache-hit != 'true'
        run: |
          curl -L -o "./butler.zip https://broth.itch.zone/butler/linux-amd64/$BUTLER_VER/archive/default"
          unzip -o ./butler.zip
          ./butler --version

      - name: Log in to butler
        run: |
          ./butler login
        env:
          BUTLER_API_KEY: ${{ secrets.BUTLER_API_KEY }}

      - name: Push to Pitch nightly
        run: |
          ./butler push ./dist/ nnda/pitch-nightly:web --userversion-file ./dist/version.txt
        env:
          BUTLER_API_KEY: ${{ secrets.BUTLER_API_KEY }}
